services:
  - type: web
    name: todoer-phoenix
    runtime: elixir
    buildCommand: "./render_build.sh"
    startCommand: "_build/prod/rel/todoer_phoenix/bin/todoer_phoenix start"
    healthCheckPath: /
    envVars:
      - key: MIX_ENV
        value: prod
      - key: PHX_SERVER
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: POOL_SIZE
        value: 10
